#config_version=5
##! mode: number_targets
mode:
  start_events: ball_starting, start_mode_number_targets
  stop_events: stop_mode_number_targets, ball_will_end
  restart_on_next_ball: true
  priority: 150


shows: 
  unlit_number_target:
    - time: 0
      lights:
        (light): 0
  lit_number_target:
    - time: 0
      lights:
        (light): ff
  flashing_number_target:
    - time: 0
      lights:
        (light): 0
    - time: '+0.25'
      duration: 0.25
      lights:
        (light): ff


shots:
  target_1:
    switch: s_target_1
    show_tokens:
      light: l_target_1
    profile: number_target
  target_2:
    switch: s_target_2
    show_tokens:
      light: l_target_2
    profile: number_target
  target_3:
    switch: s_target_3
    show_tokens:
      light: l_target_3
    profile: number_target
  target_4:
    switch: s_target_4
    show_tokens:
      light: l_target_4
    profile: number_target


shot_groups:
  number_target_group:
    debug: true
    shots: target_1, target_2, target_3, target_4
    restart_events: number_target_group_lit_complete, number_target_group_flash_complete

# variable_player:
#   number_target_group_lit_complete{current_player.star_level < 3}:
#     star_level: 1
#   number_target_group_flash_complete{current_player.star_level < 3}:
#     star_level: 1


counters:
  star_light_level:
    starting_count: 0
    count_complete_value: 3
    count_events: number_target_group_lit_complete, number_target_group_flash_complete
    events_when_complete: start_mode_number_specials
    reset_on_complete: false


shot_profiles:
  number_target:
    states:
      - name: unlit
        show: unlit_number_target
      - name: lit
        show: lit_number_target
      - name: flash
        show: flashing_number_target
        sync_ms: 250
    loop: false

# light_player:
#   "{(current_player.star_level) > 0}":
#     l_star_1: ff
#   "{(current_player.star_level) > 1}":
#     l_star_2: ff


light_player:
  "{(device.counters.star_light_level.value) > 0}":
    l_star_1: ff
  "{(device.counters.star_light_level.value) > 1}":
    l_star_2: ff
